### ISSUE TITLE
Great guide, Minor suggestions

### ISSUE THREAD

**Issue by richardhendricks** [copygirl/vintagestory-guide#1]
Hello!  20 hours in and I finally find your great guide. :)  After reading through it, I have a few minor suggestions.

1. Mention how nutrition affects HP. Getting a diverse diet can add quite a bit to HP, helping a lot with fighting the wolves.
2. Add beehives to the "waypoint this!" list. It looks like the beehive section is WIP, which is fine, but beehives/skeps can be started day 1 - just need reeds and clay - and provide one of the better resources, wax. 

Thanks!

**Comment by copygirl** [comment]
Thanks for the feedback. Unfortunately the guide is quite outdated by now, I haven't properly played the game in a good while, and my motivation is currently spent on other projects.

**Comment by copygirl** [comment]
Also, I did mention nutrition in the [Character](https://copy.mcft.net/vs/guide/#Character) section, where the character dialog is explained:

> The nutrition bars will fill up as you eat foods in those categories. You will find that *cooked meals* are an especially good way to fill multiple at once. This is important because you can raise your maximum health from 15 health points (by default) to a total of 27.5 when all 5 categories are full.

**Comment by richardhendricks** [comment]
Oh ok, sorry to hear that.  Hope you come back some time soon!
